### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by mesh17** [mesh-17/Acer-Nitro-7-AN715-51-OpenCore-Hackintosh#1]
[EFI.zip](https://github.com/imesh17/Acer-Nitro-7-AN715-51-OpenCore-Hackintosh/files/4657139/EFI.zip)

**Comment by imesh17** [comment]
[EFI.zip](https://github.com/imesh17/Acer-Nitro-7-AN715-51-OpenCore-Hackintosh/files/4657431/EFI.zip)

**Comment by imesh17** [comment]
[EFI.zip](https://github.com/imesh17/Acer-Nitro-7-AN715-51-OpenCore-Hackintosh/files/4657757/EFI.zip)

**Comment by mesh17** [comment]
23 May - test - 
[EFI.zip](https://github.com/imesh17/Acer-Nitro-7-AN715-51-OpenCore-Hackintosh/files/4671940/EFI.zip)
